const SOURCES = [
  {
    id: "servizi_salvador",
    label: "Servizi Salvador",
    listUrl: "https://www.servizisalvador.it/necrologi/",
    listingRule: {
      detailSelector: "a[href*='/necrologi/']",
      skipIfHrefEndsWith: "/necrologi/",
      skipIfTextMatches: /invia cordoglio/i,
      stripTextRegex: /\bInvia Cordoglio\b/gi,
      stripLeadingDate: true,
    },
    preferLinkedImage: true,
    ocrEligible: true,
  },
  {
    id: "ultimoviaggio",
    label: "Ultimo Viaggio",
    listUrl: "https://ultimoviaggio.it/necrologi/",
    listingRule: {
      detailSelector: "a",
      textPrefixRequired: /^Leggi tutto\s+/i,
      stripTextPrefix: /^Leggi tutto\s+/i,
      skipDateHint: true,
    },
    ocrEligible: true,
  },
  {
    id: "memorial",
    label: "Memorial",
    listUrl: "https://www.onoranzefunebrimemorial.it/necrologi/",
    listingRule: {
      detailSelector: "a[href*='/necrologio/']",
      minTitleWords: 1,
      minTitleLength: 4,
    },
    funeralDateListHintFirst: true,
    detailBodySelector: "#obituary-details, #service-details",
  },
  {
    id: "san_osvaldo",
    label: "San Osvaldo",
    listUrl: "https://onoranzefunebrisanosvaldo.it/necrologi/",
    listingRule: {
      detailSelector: "h2 a[href], h3 a[href]",
      skipListPageRegex: /\/necrologi\/?$|\/necrologi\/page\//i,
      requiredHostIncludes: "onoranzefunebrisanosvaldo.it",
      blockedUrlRegex: /\/contattaci|\/servizi|\/privacy|\/privacy-policy|\/gestione-dei-cookie|\/category\//i,
    },
    detailBodyCutoffRegex: /\bO\.?F\.?\s*S\.?\s*Osvaldo\b/i,
  },
  {
    id: "san_pietro_faldon",
    label: "Onoranze Funebri San Pietro Faldon",
    listUrl: "https://onoranzefunebrisanpietrofaldon.it/elenco-necrologi/",
    listingRule: {
      detailSelector: "h2 a[href*='/necrologi/'], h3 a[href*='/necrologi/']",
      skipListPageRegex: /\/elenco-necrologi\/?$/i,
      requiredHostIncludes: "onoranzefunebrisanpietrofaldon.it",
      blockedUrlRegex: /\/privacy|\/cookie|\/contatti|\/servizi|\/chi-siamo|\/cerimonia/i,
    },
    ocrEligible: true,
    ocrRequired: true,
    ocrPrimaryTown: true,
    ocrPrimaryFuneralDate: true,
    wpUploadsMaxAgeMonths: 2,
    detailBodyCutoffRegex: /\bCONTATTACI\b|\bSede di SAN PIETRO DI FELETTO\b|\bPompe Funebri Cappella Maggiore\b/i,
  },
  {
    id: "pfa_san_marco",
    label: "PFA San Marco",
    listUrl: "https://www.pfasanmarco.it/annunci-funebri/",
    listingRule: {
      detailSelector: "a[href*='/annuncio/']",
    },
  },
  {
    id: "zanette",
    label: "Onoranze Funebri Zanette",
    listUrl: "https://www.onoranzefunebrizanette.it/necrologi-cordogli-online-cordignano",
    listingRule: {
      detailSelector: ".postArticle a[href], a[data-blog-post-alias][href]",
      skipListPageRegex: /\/necrologi-cordogli-online-cordignano\/?$/i,
      blockedUrlRegex: /\/privacy|\/cookie|\/contatti|\/servizi|\/articoli/i,
      cardSelector: ".postArticle, article, li, div",
      listImageStyleSelector: ".blogImg",
      listImageSrcFromStyleSelector: ".blogImg img",
    },
    ocrEligible: true,
    swapFirstLastName: true,
  },
  {
    id: "salamon",
    label: "Pompe Funebri Salamon",
    listUrl: "https://www.pompefunebrisalamon.com/condoglianze-online/",
    listingRule: {
      detailSelector: "h3 a[href*='/condoglianze-online/'], h2 a[href*='/condoglianze-online/']",
      skipListPageRegex: /\/condoglianze-online\/?$/i,
    },
    preferLinkedImage: true,
    ocrEligible: true,
  },
  {
    id: "lapace_conegliano",
    label: "Onoranze Funebri La Pace Conegliano",
    listUrl: "https://www.onoranzefunebrilapaceconegliano.com/annunci-funebri/",
    listingRule: {
      detailSelector: "h2 a[href*='/annuncio/'], h3 a[href*='/annuncio/']",
      skipListPageRegex: /\/annunci-funebri\/?$/i,
      blockedUrlRegex: /\/privacy|\/cookie|\/contatti|\/servizi|\/storie-di-vita|\/socrem-tv/i,
    },
    preferLinkedImage: true,
    ocrEligible: true,
    reprocessWhenNameNoisy: true,
  },
  {
    id: "zanardo",
    label: "Agenzia Funebre Zanardo",
    listUrl: "https://www.agenziafunebrezanardo.it/condoglianze-online/",
    listingRule: {
      detailSelector: "h3 a[href*='/condoglianze-online/'], h2 a[href*='/condoglianze-online/']",
      skipListPageRegex: /\/condoglianze-online\/?$/i,
    },
    preferLinkedImage: true,
    ocrEligible: true,
  },
  {
    id: "roman",
    label: "Onoranze Funebri Roman",
    listUrl: "https://www.ofroman.com/lista-annunci-db.php",
    listingRule: {
      detailSelector: "a[href*='annuncio-db.php?uuid=']",
      cardSelector: "article, li, div, section",
    },
    ocrEligible: true,
  },
  {
    id: "sandrin",
    label: "Onoranze Funebri Sandrin",
    listUrl: "https://www.onoranzefunebrisandrin.com/necrologi/",
    listingRule: {
      detailSelector: "h2 a[href]",
      skipListPageRegex: /\/necrologi\/?$/i,
      blockedUrlRegex: /\/privacy|\/(cookie|contatti|servizi|chi-siamo|pubblicazione)/i,
      cardSelector: "article, .post, li, div",
      listImageSrcSelector: "img",
    },
    ocrEligible: true,
  },
  {
    id: "boscaia",
    label: "Onoranze Funebri Boscaia",
    listUrl: "https://boscaia.com/epigrafi.php",
    listingRule: {
      titleSelector: "h3",
      linkTextMatch: /vedi epigrafe/i,
      linkHrefMustMatch: /\/\d+\.html/,
      linkSearchDepth: 2,
      listImageSrcSelector: "img",
    },
    ocrEligible: true,
  },
  {
    id: "pederiva",
    label: "Onoranze Funebri Pederiva",
    listUrl: "https://www.onoranzefunebripederiva.com/necrologi/",
    listingRule: {
      detailSelector: "a[href]",
      requiredHostIncludes: "onoranzefunebripederiva.com",
      skipListPageRegex: /\/necrologi\/?$/i,
      blockedUrlRegex: /\/(?:chi-siamo|dove-siamo|contatti|privacy|cookie|servizi|le-memorie)/i,
      listImageSrcSelector: "img",
    },
    ocrEligible: true,
  },
  {
    id: "denadai",
    label: "Onoranze Funebri De Nadai",
    listUrl: "https://denadaionoranzefunebri.com/necrologi/",
    listingRule: {
      detailSelector: "a[href*='/necrologi/']",
      skipListPageRegex: /\/necrologi\/?(?:page\/\d+\/?)?$/i,
      blockedUrlRegex: /\/privacy|\/cookie|\/contatti|\/servizi|\/chi-siamo/i,
    },
    ocrEligible: true,
  },
  {
    id: "cof_treviso",
    label: "Casa Funeraria COF Treviso",
    listUrl: "https://www.casafunerariacof.it/necrologi/",
    listingRule: {
      detailSelector: "a[href*='/necrologio/']",
      skipListPageRegex: /\/necrologi\/?(?:page\/\d+\/?)?$/i,
      blockedUrlRegex: /\/privacy|\/cookie|\/contatti|\/servizi|\/chi-siamo/i,
    },
    ocrEligible: true,
  },
  {
    id: "sat_sacile",
    label: "Onoranze Funebri SAT",
    listUrl: "https://onoranzefunebrisat.it/necrologi/",
    listingRule: {
      detailSelector: "h6 a[href*='/necrologi/']",
      skipListPageRegex: /\/necrologi\/?$/i,
      blockedUrlRegex: /\/privacy|\/cookie|\/contatti|\/servizi|\/chi-siamo/i,
      cardSelector: ".necrologio-card, article, li, div",
      listImageSrcSelector: "img",
    },
    ocrEligible: true,
  },
  {
    id: "lamemoria_conegliano",
    label: "Onoranze Funebri La Memoria Conegliano",
    listUrl: "https://onoranzefunebrilamemoria.it/necrologi/",
    listingRule: {
      titleSelector: "h6",
      linkTextMatch: /leggi di pi/i,
      linkHrefMustMatch: /\/necrologi\//,
      skipListPageRegex: /\/necrologi\/?$/i,
      blockedUrlRegex: /\/privacy|\/cookie|\/contatti|\/servizi/i,
      linkSearchDepth: 1,
    },
  },
  {
    id: "sanmarco_vv",
    label: "Onoranze Funebri San Marco Vittorio Veneto",
    listUrl: "https://onoranzefunebrisanmarco.com/condoglianze/",
    listingRule: {
      detailSelector: "h3 a[href*='/condoglianze/']",
      skipListPageRegex: /\/condoglianze\/?$/i,
      blockedUrlRegex: /\/privacy|\/cookie|\/contatti|\/chi-siamo|\/fiori|\/servizi/i,
    },
    ocrEligible: true,
  },
  {
    id: "necrologieonline_tarzo",
    label: "NecrologieOnline Tarzo",
    listUrl: "https://www.necrologieonline.org/necrologie.php?ido=52",
    type: "necrologieonline",
    structuredTownOnly: true,
  },
  {
    id: "ofdassie",
    label: "Onoranze Funebri D'Assie",
    listUrl: "https://www.ofdassie.com/necrologi/",
    listingRule: {
      detailSelector: ".all-necrologi .necrologio-single-content > a[href*='/necrologio/']",
      skipListPageRegex: /\/necrologi\/?(?:\?.*)?$/i,
      requiredHostIncludes: "www.ofdassie.com",
      cardSelector: ".necrologio-single, .col-lg-4, article, li, div",
    },
    ocrEligible: true,
  },
];

module.exports = { SOURCES };
